/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Date: typeof import('./src/components/form-wrap/src/component/form-item-component/date/index.vue')['default']
    DatePicker: typeof import('./src/components/form-wrap/src/component/form-item-component/date/component/date-picker/index.vue')['default']
    DateRange: typeof import('./src/components/form-wrap/src/component/form-item-component/date-range/index.vue')['default']
    DateRangePicker: typeof import('./src/components/form-wrap/src/component/form-item-component/date-range/component/date-range-picker/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FormItem: typeof import('./src/components/form-wrap/src/component/FormItem.vue')['default']
    Money: typeof import('./src/components/form-wrap/src/component/form-item-component/money/index.vue')['default']
    MoneyInput: typeof import('./src/components/form-wrap/src/component/form-item-component/money/component/money-input/index.vue')['default']
    Number: typeof import('./src/components/form-wrap/src/component/form-item-component/number/index.vue')['default']
    NumberInput: typeof import('./src/components/form-wrap/src/component/form-item-component/number/component/number-input/index.vue')['default']
    ReadonlyDate: typeof import('./src/components/form-wrap/src/component/form-item-component/date/component/readonly-date/index.vue')['default']
    ReadonlyDateRange: typeof import('./src/components/form-wrap/src/component/form-item-component/date-range/component/readonly-date-range/index.vue')['default']
    ReadonlyMoney: typeof import('./src/components/form-wrap/src/component/form-item-component/money/component/readonly-money/index.vue')['default']
    ReadonlyNumber: typeof import('./src/components/form-wrap/src/component/form-item-component/number/component/readonly-number/index.vue')['default']
    ReadonlySelect: typeof import('./src/components/form-wrap/src/component/form-item-component/select/component/readonly-select/index.vue')['default']
    ReadonlyText: typeof import('./src/components/form-wrap/src/component/form-item-component/text/component/readonly-text/index.vue')['default']
    ReadonlyTextarea: typeof import('./src/components/form-wrap/src/component/form-item-component/textarea/component/readonly-textarea/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/form-wrap/src/component/form-item-component/select/index.vue')['default']
    SelectInput: typeof import('./src/components/form-wrap/src/component/form-item-component/select/component/select-input/index.vue')['default']
    Src: typeof import('./src/components/form-wrap/src/index.vue')['default']
    Text: typeof import('./src/components/form-wrap/src/component/form-item-component/text/index.vue')['default']
    Textarea: typeof import('./src/components/form-wrap/src/component/form-item-component/textarea/index.vue')['default']
    TextareaInput: typeof import('./src/components/form-wrap/src/component/form-item-component/textarea/component/textarea-input/index.vue')['default']
    TextInput: typeof import('./src/components/form-wrap/src/component/form-item-component/text/component/text-input/index.vue')['default']
  }
}
